-- Phase 4: KakaoT article footnote sample (Namu-style)
-- Safe to run multiple times.

update public.wiki_articles
set
  content = '<h2 id="what-is-kakao-t">What is KakaoT?</h2><p>KakaoT (카카오T) is Korea''s answer to Uber. It is operated by Kakao Mobility and is widely used across major cities.<sup id="fnref-1"><a href="#fn-1">[1]</a></sup></p><p><del>Before KakaoT, many foreigners survived taxi rides with map screenshots and hand gestures.</del></p><h2 id="registering-as-a-foreigner">Registering as a Foreigner</h2><p>You usually need one of the following: a Korean phone number, a verified Kakao account, or eligible foreign card setup depending on policy updates.<sup id="fnref-2"><a href="#fn-2">[2]</a></sup></p><h2 id="types-of-taxis-available">Types of Taxis Available</h2><ul><li><strong>Standard Taxi:</strong> most common and cheapest.</li><li><strong>Kakao Black:</strong> premium service with higher base fare.</li><li><strong>Large Taxi:</strong> better for groups and luggage.</li></ul><h2 id="how-to-use">How to Use</h2><ol><li>Open KakaoT and choose Taxi.</li><li>Confirm pickup and destination.</li><li>Check estimated fare and route.</li><li>Book and wait for driver match.</li></ol><h2 id="payment">Payment</h2><p>You can pay with registered cards in-app or in some cases directly to the driver. Card policy support for foreign users can vary by app/account state.<sup id="fnref-3"><a href="#fn-3">[3]</a></sup></p><h2 id="street-hailing">Street Hailing</h2><p>You can still hail taxis from the street, but in busy districts KakaoT is often faster and more predictable at night.</p><h2 id="references">References</h2><p id="fn-1"><a href="#fnref-1">[1]</a> Kakao Mobility official service overview.</p><p id="fn-2"><a href="#fnref-2">[2]</a> Kakao account/verification and signup help pages.</p><p id="fn-3"><a href="#fnref-3">[3]</a> In-app payment and card registration guidance.</p>',
  updated_at = now(),
  last_updated = current_date
where slug = 'kakao-t';
